### ISSUE TITLE
Absolutely Useless!

### ISSUE THREAD

**Issue by stevef9432203** [djjudas21/puppet-lm_sensors#6]
I cane across this and thought it might help get my Gigabye eypc dual mobo set up for lmsensors, You assume too much.  Puppet is installed and what do I do next? No useful Examples?  So What the !!!@###  do I do...

Steven Foster

**Comment by stevef9432203** [comment]
Crapolla.  Nice new Miilstone in the Road..

**Comment by djjudas21** [comment]
I'm sorry you haven't been able to figure this out. Assuming your Puppet environment is installed, configured and working, literally all you need to do is include `class { '::lm_sensors': }` in your server's manifest. This is included in the README of this module, along with some sample code to override config for a specific sensor. I consider that a useful example.

A Puppet tutorial is out of scope here, but you can get decent [support from Puppet](https://www.puppet.com/support) themselves.

As a side note, I didn't understand your remark
> Crapolla. Nice new Miilstone in the Road..

but I have taken the liberty of creating a GitHub milestone called [Crapolla](https://github.com/djjudas21/puppet-lm_sensors/milestone/1).

Hope this helps!
